language: ruby
rvm: 2.2.6
sudo: false
cache:
  directories:
    - vendor/bundle
before_install: |
  bundle install --deployment --jobs=3 --retry=3
script: test $TRAVIS_PULL_REQUEST != "false" || test $TRAVIS_BRANCH != "translation" || ./travis-build.sh
branches:
  only:
    - translation
