name: Crystal 程式語言
description: Ruby 風格但可編譯的程式語言
url: http://crystal-tw.github.io
logo: /images/crystal-h.png
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      image: /images/icon.png
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      image: /images/icon.png
      layout: post
      is_post: true
twitter:
  username: CrystalLanguage

highlighter: rouge
markdown: kramdown
exclude: ["Gemfile", "Gemfile.lock", "Rakefile", "scripts/*.cr", "vendor", "build"]
gems:
  - jekyll-seo-tag
  - jekyll-assets
  - jekyll-timeago

google_calendar_api_key: 'AIzaSyCv-2Npqm0mwmwVCKX8xDPhwtP_8HwCWCE'
google_calendar_id: '0s0pa4k3fov71e4itn79atlmeg@group.calendar.google.com'

assets:
  assets:
    - "*.svg"
    - "*.png"
    - "bundle.css"
